### ISSUE TITLE
Bug when changing event timing.

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/SNTC-Calendar#11]
Let's say I have an event from 8-10 pm. We can't change it to 7-9 pm because it clashes with itself.

**Comment by abhijeetmanhas** [comment]
Yes, this is a issue, since I haven't used update procedure, for changing event, we have to first delete it and then add new, I will look into it

**Comment by abhigyank** [comment]
I think this is the issue even in changing the name, or other details. Basically editing the event. Would be good to have this fixed.

**Comment by abhijeetmanhas** [comment]
This is resolved, can be closed now
