### ISSUE TITLE
Allow overlapping events

### ISSUE THREAD

**Issue by Swapnilr1** [KamandPrompt/SNTC-Calendar#17]
Some events may overlap during fests (like Utkarsh), show a prominent warning before adding but do allow overlapping events to be added anyway.

**Comment by abhijeetmanhas** [comment]
We have some options:
1) warning
2) overlapping events can only be added by superadmin
3) There is a button in the app, switch it on to add overlapping event, switch it off to disallow
4) new optional field while adding event, allow overlap or not , default no

Which may be the best choice, or better than these all three? @Swapnilr1 @abhigyank ?

**Comment by Swapnilr1** [comment]
Option 1 and 2 seem like good ideas. 

A clarification on option 4 - do both overlapping events need to have the field set to yes?

**Comment by abhigyank** [comment]
I feel a combination of (1 and 3) or option 4th would be suitable. 
Can choose either.

**Comment by abhijeetmanhas** [comment]
So I think if the event is overlapping, a dialogue box appears, and then asks for "allow overlap with X club event" seems the best..
What you say?

**Comment by abhijeetmanhas** [comment]
This was fixed by #22
