### ISSUE TITLE
Option to add event to Google calendar

### ISSUE THREAD

**Issue by abhijeetmanhas** [KamandPrompt/SNTC-Calendar#32]
App might require supporting all educational email accounts, a button of calendar to invite and add event to your calendar easily.

**Comment by LalitNM** [comment]
@code-ash-IIT you can start working on this.

**Comment by LalitNM** [comment]
Looks like #41 doesn't fix the issue for Microsoft Edge. There is no option to add the event to calendar.
Screenshot:

![image](https://user-images.githubusercontent.com/63332774/148192516-54f2be3d-bcb2-45bd-9932-568fca73645d.png)

**Comment by code-ash-IIT** [comment]
Ok will look into this..

**Comment by code-ash-IIT** [comment]
While making button from scratch, I have faced following issue..
<img width="396" alt="Screenshot 2022-01-06 at 2 26 18 PM" src="https://user-images.githubusercontent.com/76936297/148356803-52d865bf-3ff0-4391-ac7f-145834e5d4d3.png">
Date-time format should be ISO 8601, in the gCal-Link,
I am not much familiar with code-base,django and cannot find the start_time or end_time variables in code. Although I am looking into it, but it would be helpful if you could tell how to change {{event.start_time|date:"G:i"}} to iso format.
@LalitNM @abhijeetmanhas 
<img width="612" alt="Screenshot 2022-01-06 at 2 33 37 PM" src="https://user-images.githubusercontent.com/76936297/148357500-e97bea7d-5843-4a27-9987-950f24c70f5c.png">
If i use {{event.start_time|date:"G:i"}}, I get error above

**Comment by code-ash-IIT** [comment]
Above issue is fixed, 
Now the url contains time, but event.day is not in corect format..
<img width="385" alt="Screenshot 2022-01-06 at 3 22 24 PM" src="https://user-images.githubusercontent.com/76936297/148364320-067bb2f1-c9e7-49ac-8a46-6855ac775ade.png">
Below is the current format of event.day showing on website
<img width="208" alt="Screenshot 2022-01-06 at 3 23 53 PM" src="https://user-images.githubusercontent.com/76936297/148364434-1fb577e6-f819-4095-a84d-f7125c313081.png">
i want to change it to iso format, It would help, if you could tell where is event.day defined in the codebase.
