### ISSUE TITLE
Add 11:59 pm to default time drop downs for easier additions

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/SNTC-Calendar#5]

**Comment by abhijeetmanhas** [comment]
I will do this. @vsvipul will it be nice to remove seconds in entering time?

**Comment by vsvipul** [comment]
Yes.. please remove the seconds too. Thanks.

**Comment by abhijeetmanhas** [comment]
May be this issue can be closed now, default time has been added, it can't be done in dropdown since it is a library function, but it will be dealt with in future pr, without django default admin
